import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import Vue from "vue";
import {
  faAddressCard,
  faBars,
  faCamera,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCubes,
  faDownload,
  faEllipsisH,
  faEllipsisV,
  faEyeSlash,
  faFile,
  faFileAudio,
  faFileImage,
  faFileVideo,
  faFolder,
  faFolderPlus,
  faHdd,
  faHome,
  faInfo,
  faLink,
  faLock,
  faLockOpen,
  faPaperPlane,
  faPencilAlt,
  faSave,
  faSearch,
  faShare,
  faSort,
  faSyncAlt,
  faTh,
  faThList,
  faTimes,
  faTrashAlt,
  faUpload,
  faUser,
  faUserEdit,
  faUserFriends,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faAddressCard,
  faBars,
  faCamera,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCubes,
  faDownload,
  faEllipsisH,
  faEllipsisV,
  faEyeSlash,
  faFile,
  faFileAudio,
  faFileImage,
  faFileVideo,
  faFolder,
  faFolderPlus,
  faHdd,
  faHome,
  faInfo,
  faLink,
  faLock,
  faLockOpen,
  faPencilAlt,
  faSave,
  faSearch,
  faShare,
  faSort,
  faSyncAlt,
  faTh,
  faThList,
  faTimes,
  faTrashAlt,
  faUpload,
  faUser,
  faUserEdit,
  faUserFriends,
  faPaperPlane,
);

Vue.component("FontAwesomeIcon", FontAwesomeIcon);
